### ISSUE TITLE
feature request - sample based on percentile latency

### ISSUE THREAD

**Issue by maplebed** [honeycombio/dynsampler-go#3]
It would be nice to be able to set your dynamic sampling to use the latency of the event as part of the key for determining the sample rate, where the 50th percentile gets sampled most heavily and the 1% and 99% get sampled least heavily (with a curve of sample rate applied).

It is clear how to build this with the existing interface if you wish to use *only* a latency as your key, but I think allowing a combination of string key and percentile key might require adding an additional interface to the package.

**Comment by nathanleclaire** [comment]
+1

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
